
import { TranslationDictionary } from './types';

export const en: TranslationDictionary = {
  header: {
    title: "VectorCraft AI",
    subtitle: "Powered by Gemini 3 Pro",
    docs: "Documentation",
  },
  tabs: {
    create: "Genesis (Create)",
    transform: "Reconstruction (Edit)",
  },
  hero: {
    title: "What do you want to create?",
    subtitle: "Describe an object, define the style, and we'll engineer the vector art.",
    titleTransform: "Refine & Animate",
    subtitleTransform: "Upload an existing SVG to upgrade its logic, style, or motion.",
  },
  inputs: {
    sourceSvgLabel: "Source SVG Code / File",
    sourceSvgPlaceholder: "Paste SVG code here or upload a file...",
    objectLabel: "Object Description",
    objectPlaceholder: "e.g. A futuristic cyberpunk helmet...",
    transformLabel: "Transformation Goals",
    transformPlaceholder: "e.g. Change colors to gold, make lines thicker, simplify shapes...",
    styleLabel: "Visual Style",
    stylePlaceholder: "e.g. Flat design, neon colors, thin strokes...",
    techLabel: "Functional & Motion Specs",
    techPlaceholder: "e.g. Rotate the gear infinitely, add hover glow effect, pulse animation...",
    resolutionLabel: "Canvas Resolution",
    customRes: "Custom",
    urlsLabel: "Reference URLs",
    urlsPlaceholder: "https://dribbble.com/shots/...",
    intelligenceLabel: "Intelligence",
    searchLabel: "Google Search",
    dropzoneDefault: "Drop images/SVG, paste (Ctrl+V)",
    dropzoneDragging: "Release to attach",
    pasteLabel: "Paste Clipboard",
    addOptions: "Advanced Specs",
    hideOptions: "Hide Specs",
    generateButton: "Generate",
    transformButton: "Transform",
    generatingButton: "Processing...",
  },
  preview: {
    resultTitle: "Result",
    copyTooltip: "Copy SVG Code",
    downloadButton: "Export",
    downloadSvg: "Download SVG",
    downloadPng: "Download PNG",
    downloadZip: "Download ZIP (All)",
    generatedBy: "Generated by Gemini 3 Pro",
    emptyStateTitle: "Awaiting Input",
    emptyStateDesc: "Generated artwork will appear here",
    emptyStateDescShort: "Artwork area",
    bgDark: "Dark",
    bgLight: "Light",
    bgGrid: "Grid"
  },
  history: {
    title: "Production Log",
    empty: "No production history yet.",
    restore: "Restore",
    delete: "Delete",
    clearAll: "Clear Log"
  },
  refine: {
    label: "Dialectical Refinement (Aufhebung)",
    placeholder: "What contradictions should be resolved? (e.g. remove sharp corners)",
    button: "Synthesize",
    processing: "Refining...",
  },
  errors: {
    generationFailed: "Generation Failed",
    defaultDetails: "An unexpected error occurred while contacting Gemini.",
  },
  suggestions: {
    camera: 'Retro Camera',
    rocket: 'Space Rocket',
    bird: 'Origami Bird',
    house: 'Isometric House'
  }
};
